'use client'
import React, { useState } from "react";
import { motion } from "framer-motion";
import CountUp from "react-countup";
import { FileText, CheckCircle, AlertTriangle, Scale, Swords, Play, Lock, Sparkles } from "lucide-react";
import axios from 'axios';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useAuth } from "../../../context/AuthContext";
import PaywallModal from "../../PaywallModal";
import { hasAccess } from "../../../utils/planBorders";

const JudgeAI = () => {
    const { user } = useAuth();
    const [showPaywall, setShowPaywall] = useState(false);
    const [analyzing, setAnalyzing] = useState(false);
    const [result, setResult] = useState(null);
    const [caseInput, setCaseInput] = useState("");
    const [assignedJudge, setAssignedJudge] = useState("");
    const [courtType, setCourtType] = useState("");
    const [opposingParty, setOpposingParty] = useState("");

    const generatePDF = () => {
        const usageCount = user?.aiUsage?.count || 0;
        if (!hasAccess(user?.plan, 'LEGAL_RESEARCH', usageCount)) { // Using Research level as proxy
            setShowPaywall(true);
            return;
        }

        const doc = new jsPDF();

        // BRANDING HEADER
        doc.setFillColor(79, 70, 229); // Indigo 600
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("NyayNow Legal Intelligence", 14, 25);
        doc.setFontSize(10);
        doc.text("CONFIDENTIAL STRATEGY REPORT", 14, 32);

        // METADATA
        doc.setTextColor(50, 50, 50);
        doc.setFontSize(10);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 50);
        doc.text(`Case ID: ${result.caseId}`, 160, 50);

        // EXECUTIVE SUMMARY
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("Executive Summary", 14, 60);
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 62, 196, 62);

        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        const splitAnalysis = doc.splitTextToSize(result.analysis || "Analysis pending.", 180);
        doc.text(splitAnalysis, 14, 70);

        // STATS TABLE
        autoTable(doc, {
            startY: 90,
            head: [['Win Probability', 'Risk Level', 'AI Confidence']],
            body: [[`${result.winProbability}%`, result.riskLevel, `${result.confidenceScore}%`]],
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] }
        });

        // STRATEGY STEPS
        const finalY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("Strategic Counsel", 14, finalY);
        doc.line(14, finalY + 2, 196, finalY + 2);

        const strategies = result.strategy?.map((s, i) => [`${i + 1}. ${s}`]) || [];
        autoTable(doc, {
            startY: finalY + 5,
            body: strategies,
            theme: 'plain',
            styles: { fontSize: 11, cellPadding: 2 }
        });

        // FOOTER
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by NyayNow AI Justice Engine. Grounded in BNS 2024 & Live Judicial Precedents.", 105, pageHeight - 10, { align: 'center' });

        doc.save("NyayNow_Legal_Strategy.pdf");
        toast.success("Dossier Downloaded Successfully");
    };

    const handleAnalyze = async () => {
        const usageCount = user?.aiUsage?.count || 0;
        if (!hasAccess(user?.plan, 'LEGAL_RESEARCH', usageCount)) {
            setShowPaywall(true);
            return;
        }

        if (!caseInput.trim()) {
            toast.error("Please enter case details first.");
            return;
        }

        setAnalyzing(true);
        setResult(null);

        try {
            const activeCaseContext = {
                caseTitle: `Case vs ${opposingParty || 'Unknown'}`,
                caseType: courtType || "General Legal",
                caseDescription: caseInput,
                oppositionDetails: opposingParty,
                assignedJudge: assignedJudge
            };
            
            localStorage.setItem("nyaynow_active_case", JSON.stringify(activeCaseContext));

            const res = await axios.post('/api/ai/predict-outcome', activeCaseContext);

            if (res.data) {
                setResult({
                    caseId: res.data.case_id || `REF-${Math.floor(Math.random() * 10000)}`,
                    winProbability: parseInt(res.data.win_probability) || 75,
                    riskLevel: res.data.risk_level || "Medium",
                    keyPrecedents: res.data.precedent_count || 12,
                    confidenceScore: res.data.confidence_percentage || 88,
                    sentiment: "Neutral",
                    analysis: (res.data.strategy && res.data.strategy.length > 0) ? res.data.strategy[0] : "Analysis complete.",
                    risks: res.data.risk_analysis || [],
                    strategy: res.data.strategy || [],
                    precedent: res.data.relevant_precedent
                });
                toast.success("Strategic Analysis Complete");
            }
        } catch (err) {
            console.error("❌ AI Error Details:", err.response?.data || err.message);
            const errorMsg = err.response?.data?.details || err.response?.data?.message || err.response?.data?.error || "AI Overload. Please try again.";
            toast.error(errorMsg);
            setResult(null);
        } finally {
            setAnalyzing(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#0c1220] text-slate-400 font-sans selection:bg-indigo-500/30">

            {/* HERO SECTION */}
            <section className="relative pt-24 md:pt-36 pb-20 overflow-hidden">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-indigo-500/20 blur-[150px] rounded-full pointer-events-none mix-blend-screen"></div>

                <div className="container mx-auto px-6 relative z-10 text-center">
                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>
                        <span className="px-4 py-1.5 rounded-full border border-white/10 bg-white/5 text-indigo-400 text-xs font-bold uppercase tracking-[0.2em] mb-6 inline-block shadow-sm backdrop-blur-md">
                            Predictive Justice Engine
                        </span>
                        <h1 className="text-5xl md:text-7xl font-serif font-bold mb-6 tracking-tight text-white">
                            Judge <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">AI</span>
                        </h1>
                        <p className="text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed font-light">
                            AI-Powered Strategic Counsel. Analyze win probability, identify risks, and get actionable legal strategy.
                        </p>
                    </motion.div>
                </div>
            </section>

            {/* MAIN INTERFACE */}
            <section className="container mx-auto px-6 pb-24 max-w-5xl">

                {/* INPUT AREA */}
                <div className="bg-[#0f172a] border border-white/10 rounded-3xl p-10 backdrop-blur-xl shadow-2xl mb-8">
                    {!result && !analyzing && (
                        <div className="space-y-6">
                            <div>
                                <h3 className="text-2xl font-bold mb-6 text-white tracking-tight">Case Parameters</h3>
                                
                                <div className="grid md:grid-cols-3 gap-4 mb-6">
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Court Type / Jurisdiction</label>
                                        <input
                                            type="text"
                                            value={courtType}
                                            onChange={(e) => setCourtType(e.target.value)}
                                            placeholder="e.g. Delhi High Court"
                                            className="w-full bg-black/20 border border-white/10 rounded-xl p-4 text-white focus:outline-none focus:border-indigo-500/50 transition placeholder-slate-600"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Assigned Justice</label>
                                        <input
                                            type="text"
                                            value={assignedJudge}
                                            onChange={(e) => setAssignedJudge(e.target.value)}
                                            placeholder="e.g. Justice D.Y. Chandrachud"
                                            className="w-full bg-black/20 border border-white/10 rounded-xl p-4 text-white focus:outline-none focus:border-indigo-500/50 transition placeholder-slate-600"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Opposing Party / Counsel</label>
                                        <input
                                            type="text"
                                            value={opposingParty}
                                            onChange={(e) => setOpposingParty(e.target.value)}
                                            placeholder="e.g. Reliance Industries"
                                            className="w-full bg-black/20 border border-white/10 rounded-xl p-4 text-white focus:outline-none focus:border-indigo-500/50 transition placeholder-slate-600"
                                        />
                                    </div>
                                </div>
                                
                                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Case Facts & Arguments</label>
                                <textarea
                                    value={caseInput}
                                    onChange={(e) => setCaseInput(e.target.value)}
                                    placeholder="Paste comprehensive case details, legal notices, or situation descriptions here for deep mathematical analysis..."
                                    className="w-full h-40 bg-black/20 border border-white/10 rounded-xl p-4 text-white focus:outline-none focus:border-indigo-500/50 transition resize-none custom-scrollbar text-sm leading-relaxed"
                                />
                            </div>
                            <div className="flex justify-center">
                                <button
                                    onClick={handleAnalyze}
                                    className="px-10 py-4 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition shadow-lg shadow-indigo-600/30 hover:shadow-indigo-600/50 flex items-center gap-2 group"
                                >
                                    <Play size={20} className="group-hover:translate-x-1 transition" /> Analyze Strategy
                                </button>
                            </div>
                        </div>
                    )}

                    {analyzing && (
                        <div className="text-center py-10">
                            <div className="relative w-32 h-32 mx-auto mb-8">
                                <div className="absolute inset-0 border-4 border-indigo-500/30 rounded-full"></div>
                                <div className="absolute inset-0 border-4 border-indigo-500 rounded-full border-t-transparent animate-spin"></div>
                                <Scale className="absolute inset-0 m-auto text-indigo-400" size={40} />
                            </div>
                            <h3 className="text-2xl font-bold mb-2 animate-pulse text-white">Formulating Legal Strategy...</h3>
                            <p className="text-slate-400">Consulting Live Judicial Precedents (BNS 2024)</p>
                        </div>
                    )}

                    {result && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-left space-y-8">

                            {/* Mandantory Legal Disclaimer */}
                            <div className="mb-6 p-4 rounded-2xl bg-amber-500/5 border border-amber-500/10 flex items-start gap-3">
                                <AlertTriangle size={18} className="text-amber-500 mt-0.5 shrink-0" />
                                <div>
                                    <p className="text-xs text-amber-200/90 font-bold uppercase tracking-wider mb-1">AI Prediction — Not Legal Advice</p>
                                    <p className="text-[11px] text-slate-500 leading-relaxed">
                                        The win probability and strategy provided are generated by an AI model grounded in real-time search data. This is <span className="text-white underline">NOT</span> a guarantee of outcome. Always verify with a legal professional.
                                    </p>
                                </div>
                            </div>

                            {/* TOP STATS ROW */}
                            <div className="grid md:grid-cols-4 gap-4">
                                <div className="bg-white/5 p-6 rounded-2xl border border-white/10 text-center relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-emerald-500"></div>
                                    <p className="text-slate-400 text-[10px] font-black uppercase tracking-wider mb-2">Win Prob.</p>
                                    <div className="text-4xl font-bold text-emerald-400 mb-1">
                                        <CountUp end={result.winProbability} duration={2} suffix="%" />
                                    </div>
                                    <p className="text-[9px] text-emerald-500/80 font-bold uppercase tracking-tighter">Case Strength</p>
                                </div>
                                <div className="bg-white/5 p-6 rounded-2xl border border-white/10 text-center relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-amber-500"></div>
                                    <p className="text-slate-400 text-[10px] font-black uppercase tracking-wider mb-2">Risk Level</p>
                                    <div className="text-2xl font-bold text-amber-400 mb-1 h-9 flex items-center justify-center uppercase">{result.riskLevel}</div>
                                    <p className="text-[9px] text-amber-500/80 font-bold uppercase tracking-tighter">Procedural</p>
                                </div>
                                <div className="bg-white/5 p-6 rounded-2xl border border-white/10 text-center relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-blue-500"></div>
                                    <p className="text-slate-400 text-[10px] font-black uppercase tracking-wider mb-2">Precedents</p>
                                    <div className="text-3xl font-bold text-blue-400 mb-1 h-9 flex items-center justify-center">{result.keyPrecedents}</div>
                                    <p className="text-[9px] text-blue-500/80 font-bold uppercase tracking-tighter">Live Mentions</p>
                                </div>
                                <div className="bg-white/5 p-6 rounded-2xl border border-white/10 text-center relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-indigo-500"></div>
                                    <p className="text-slate-400 text-[10px] font-black uppercase tracking-wider mb-2">AI Confidence</p>
                                    <div className="text-4xl font-bold text-indigo-400 mb-1">
                                        <CountUp end={result.confidenceScore} duration={2} suffix="%" />
                                    </div>
                                    <p className="text-[9px] text-indigo-500/80 font-bold uppercase tracking-tighter">Grounding Rank</p>
                                </div>
                            </div>

                            {/* STRATEGY SECTION */}
                            <div className="bg-indigo-900/10 border border-indigo-500/30 rounded-2xl p-6 relative overflow-hidden">
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="w-10 h-10 rounded-full bg-indigo-500/20 flex items-center justify-center text-indigo-400">
                                        <Swords size={20} />
                                    </div>
                                    <h3 className="text-xl font-serif font-bold text-white">Strategic Counsel</h3>
                                </div>
                                <ul className="space-y-4">
                                    {result.strategy && result.strategy.map((item, idx) => (
                                        <li key={idx} className="flex gap-4 text-slate-300 leading-relaxed">
                                            <span className="text-indigo-400 font-black text-xs mt-1 border border-indigo-500/30 w-6 h-6 rounded-lg flex items-center justify-center bg-indigo-500/10 shrink-0">{idx + 1}</span>
                                            <span className="text-sm">{item}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            {/* PRECEDENT CARD */}
                            <div className="bg-white/5 border border-white/10 rounded-2xl p-6 relative overflow-hidden group">
                                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition">
                                    <Sparkles size={40} className="text-amber-500" />
                                </div>
                                <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-3 flex items-center gap-2">
                                    <Scale size={12} /> Key Legal Precedents (Live)
                                </h4>
                                <p className="text-base font-serif italic text-white leading-relaxed">"{result.precedent || "Fetching real-time case law..."}"</p>
                            </div>

                            <div className="flex justify-between items-center pt-8 border-t border-white/10">
                                <button
                                    onClick={generatePDF}
                                    className="px-6 py-3 rounded-xl bg-white/5 border border-white/10 text-white font-bold text-sm hover:bg-white/10 transition flex items-center gap-2"
                                >
                                    <FileText size={16} />
                                    Download Dossier
                                    {user?.plan !== 'gold' && <Lock size={14} className="text-amber-400" />}
                                </button>
                                <button onClick={() => setResult(null)} className="text-sm text-slate-500 hover:text-white underline underline-offset-8 font-bold uppercase tracking-widest">Restart Simulation</button>
                            </div>

                        </motion.div>
                    )}
                </div>
            </section>

            <PaywallModal isOpen={showPaywall} onClose={() => setShowPaywall(false)} feature="Deep Justice Insights" />
            <div className="pb-20" />
        </div>
    );
};

export default JudgeAI;
