"use client"
import React from 'react';
import { motion } from 'framer-motion';
import { AlertOctagon, Scale, ShieldAlert, Sparkles, BookOpen } from 'lucide-react';

const Disclaimer = () => {
    return (
        <div className="min-h-screen bg-[#020617] text-slate-300 py-24 px-6 md:px-12 lg:px-24">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-4xl mx-auto"
            >
                <div className="flex items-center gap-4 mb-12">
                    <div className="w-12 h-12 rounded-xl bg-amber-600/20 border border-amber-500/20 flex items-center justify-center">
                        <AlertOctagon size={24} className="text-amber-500" />
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight">Legal Disclaimer</h1>
                </div>

                <div className="space-y-12">
                    <section className="p-8 rounded-[32px] bg-amber-500/5 border border-amber-500/20">
                        <p className="text-sm text-amber-400 font-bold uppercase tracking-widest mb-2 flex items-center gap-2">
                            <ShieldAlert size={16} /> AI Output Notification
                        </p>
                        <p className="text-white text-lg leading-relaxed font-bold">
                            All outputs generated by the NyayNow AI, including legal document templates, win probability simulations, and automated analyses, are intended exclusively as legal information for educational purposes. They do not constitute formal legal advice or create any attorney-client relationship.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <Scale size={20} className="text-amber-400" />
                            1. No Attorney-Client Relationship
                        </h2>
                        <p className="leading-relaxed">
                            Your use of NyayNow, including interactions with the AI assistant, document drafting tools, or case outcome predictors, does not establish an attorney-client relationship between you and NyayNow. The platform acts as a legal technology provider only. Professional legal representation should be secured separately from a qualified, registered advocate.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <Sparkles size={20} className="text-amber-400" />
                            2. AI Accuracy and Limitations
                        </h2>
                        <p className="leading-relaxed">
                            AI-generated responses, win probabilities, and risk score predictions are mathematical simulations based on training data and live Indian statutory references (BNS 2024, BNSS, BSA). Because judicial processes are highly contextual and dynamic, NyayNow does not guarantee the factual accuracy, completeness, or real-world applicability of AI outputs. Users must verify all references with registered advocates.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <BookOpen size={20} className="text-amber-400" />
                            3. Use of Document Templates
                        </h2>
                        <p className="leading-relaxed">
                            Document drafts created in the Autonomous Drafting Lab are starting templates. Drafting notice details, state-specific stamp duty calculations, and specific contract clauses require verification. NyayNow assumes no liability for void clauses, enforceability disputes, or contractual failures resulting from the use of AI-generated documents.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <ShieldAlert size={20} className="text-amber-400" />
                            4. Marketplace Directory Status
                        </h2>
                        <p className="leading-relaxed">
                            The Lawyer Marketplace directory is designed in accordance with the Bar Council of India (BCI) regulations. The listings are based on factual information provided by registered advocates (areas of specialization, years of experience, jurisdiction). Listings do not constitute advertisements, solicitations, or recommendations by NyayNow.
                        </p>
                    </section>

                    <section className="p-6 rounded-2xl bg-white/5 border border-white/10 italic text-sm">
                        Please consult a qualified advocate for official legal queries. Last updated: November 2025.
                    </section>
                </div>
            </motion.div>
        </div>
    );
};

export default Disclaimer;
